# Generated by Django 4.1.4 on 2022-12-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(auto_now_add=True, verbose_name="Data inicial"),
                ),
                (
                    "task_number",
                    models.DecimalField(
                        decimal_places=4, max_digits=7, verbose_name="Número tarefa"
                    ),
                ),
                (
                    "ssi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=7,
                        null=True,
                        verbose_name="Número SSI",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "font_name",
                    models.CharField(max_length=50, verbose_name="Nome fonte"),
                ),
                (
                    "final_opnion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Parecer Final"
                    ),
                ),
                (
                    "started",
                    models.BooleanField(default=False, verbose_name="Iniciada"),
                ),
                (
                    "finished",
                    models.BooleanField(default=False, verbose_name="Finalizada"),
                ),
                (
                    "submeted",
                    models.BooleanField(default=False, verbose_name="Submetido"),
                ),
            ],
            options={
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
            },
        ),
    ]
